# Generated by Django 5.0.6 on 2024-07-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('stipend', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('lastDateOfApply', models.DateField()),
                ('domain', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
