# Generated by Django 5.0.6 on 2024-07-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_name_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('ldap_id', models.CharField(max_length=50)),
            ],
        ),
    ]
