# Generated by Django 5.0.6 on 2024-07-13 00:37

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume1',
            field=models.FileField(blank=True, null=True, upload_to='one_page_resumes/', validators=[users.models.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='user',
            name='resume2',
            field=models.FileField(blank=True, null=True, upload_to='two_page_resumes/', validators=[users.models.validate_file_extension]),
        ),
    ]
